# Generated by Django 2.2.7 on 2019-11-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fechapublicacion',
            field=models.DateTimeField(),
        ),
    ]
