# Generated by Django 2.2.7 on 2019-11-20 19:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='contenido',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
